language: python
python:
- '3.6'
before_script:
- pip3 install -r requirements.txt
- python manage.py migrate
script:
- coverage run --source='authors' manage.py test
- coverage report
after_success:
- coveralls