language: python
python:
- '3.6'
services:
  - postgresql
before_script:
- pip3 install -r requirements.txt
- psql -c 'create database authorheaven;' -U postgres
- python manage.py migrate
script:
- coverage run --source='authors' manage.py test
- coverage report
after_success:
- coveralls